exp_name: 'stage2'
output_dir: './redo'
seed: 42
resume_from_checkpoint: ''

stage1_ckpt_step: null
stage1_ckpt_dir: '/scratch/cs/faceedit/mengting/projects/AUAnimation/redo/stage1/used-98087'  # stage1 checkpoint folder

checkpointing_steps: 2000
save_model_epoch_interval: 1


data:
  train_bs: 2
  video_dirs: ['/scratch/cs/faceedit/mengting/data/CelebV-HQ/videos'] # Your data root folder
  render_dirs: ['/scratch/cs/faceedit/mengting/data/CelebV-HQ/render_videos']
  guids: 
    - 'render'
  image_size: 512
  bbox_crop: true
  aug_type: "Resize"
  sample_frames: 12
  sample_rate: 5


validation:
  validation_steps: 1000
  clip_length: 6
  ref_images:
    - validation_data/ref_images/frame_0000.jpg
  guidance_folders:
    - validation_data/guid_sequences/0
  guidance_indexes: [0, 30, 60, 90, 120]


solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: False
  gradient_checkpointing: False
  max_train_steps: 100000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: False
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

guidance_encoder_kwargs:
  guidance_embedding_channels: 320
  guidance_input_channels: 3
  block_out_channels: [16, 32, 96, 256]

unet_additional_kwargs:
  use_inflated_groupnorm: true
  unet_use_cross_frame_attention: false 
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: true 
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1

base_model_path: '/scratch/cs/faceedit/mengting/diffusion_models/stable-diffusion-v1-5'
vae_model_path: '/scratch/cs/faceedit/mengting/diffusion_models/sd-vae-ft-mse'
image_encoder_path: '/scratch/cs/faceedit/mengting/diffusion_models/image_encoder'
mm_path: '/scratch/cs/faceedit/mengting/diffusion_models/animate_diff/mm_sd_v15_v2.ckpt'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
